version: "3"

services:
  app:
    image: node:16-alpine3.11
    working_dir: /var/www/node
    command: sh -c "npm install && npm run dev"
    restart: unless-stopped
    volumes:
      - .:/var/www/node
    ports:
    - ${PORT_PRODUCTION}:8080
    expose:
      - ${PORT_PRODUCTION}
    environment:
      - ENV=${ENV}